services:
    frontend:
        container_name: frontend
        build: .
        develop:
            watch:
                - action: sync
                  path: ./src
                  target: /app/src
                - action: sync
                  path: ./public
                  target: /app/public
                  ignore:
                      - node_modules/
                - action: rebuild
                  path: package.json
                - action: rebuild
                  path: next.config.json
        environment:
            - NODE_ENV=development
        env_file:
            - .env
        restart: always
        ports:
            - 3000:3000
        networks:
            - matchday

networks:
    matchday:
        external: true
